import os
import zipfile
import io
import requests
import json
from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_ollama import ChatOllama
from langchain_core.messages import SystemMessage, HumanMessage

class AgentState(TypedDict):
    repo_name: str
    run_id: str
    github_token: str
    parsed_logs: str
    root_cause: str
    suggested_fix_code: str
    pr_url: str

# NODE 1: Fetch Failed Logs
def fetch_logs_node(state: AgentState) -> AgentState:
    print("\n[Node 1] Fetching failed run logs from GitHub API...")
    url = f"https://api.github.com/repos/{state['repo_name']}/actions/runs/{state['run_id']}/logs"
    headers = {
        "Authorization": f"Bearer {state['github_token']}",
        "Accept": "application/vnd.github+json"
    }

    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        state['parsed_logs'] = "Failed to fetch logs."
        return state

    logs_content = ""
    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        for filename in z.namelist():
            if "test" in filename.lower() or "run" in filename.lower():
                with z.open(filename) as f:
                    logs_content += f.read().decode('utf-8', errors='ignore')

    cleaned_logs = logs_content[-3000:] if len(logs_content) > 3000 else logs_content
    state['parsed_logs'] = cleaned_logs
    return state

# NODE 2: Root Cause Analysis
def analyze_root_cause_node(state: AgentState) -> AgentState:
    print("\n[Node 2] Analyzing logs with Ollama (Llama 3.2)...")
    llm = ChatOllama(model="llama3.2", temperature=0)

    system_prompt = "You are a DevOps AI agent. Identify exact root cause, failed file, line number, and error type concisely."
    user_prompt = f"Failed Logs:\n```\n{state['parsed_logs']}\n```"

    response = llm.invoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)])
    state['root_cause'] = response.content
    print(f"\n[Root Cause]:\n{state['root_cause']}\n")
    return state

# NODE 3: Generate Code Fix
def generate_fix_node(state: AgentState) -> AgentState:
    print("\n[Node 3] Generating code fix for test_app.py...")
    
    # Intentionally replacing failing test code string directly
    # In a real scenario, LLM writes file diff; here we generate updated code for test_app.py
    fixed_code = """import pytest
from app import app

@pytest.fixture
def client():
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

def test_home_route(client):
    response = client.get('/')
    assert response.status_code == 200
    assert response.json["status"] == "healthy"

def test_intentional_failure(client):
    response = client.get('/')
    assert response.json["status"] == "healthy"  # Fixed by AI Agent
"""
    state['suggested_fix_code'] = fixed_code
    print("[Node 3] Code fix generated successfully.")
    return state

# NODE 4: Auto PR Creation via GitHub API
def create_pr_node(state: AgentState) -> AgentState:
    print("\n[Node 4] Creating Automated Pull Request on GitHub...")
    token = state['github_token']
    repo = state['repo_name']
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }

    # 1. Get main branch SHA
    main_ref = requests.get(f"https://api.github.com/repos/{repo}/git/ref/heads/main", headers=headers).json()
    base_sha = main_ref['object']['sha']

    # 2. Create new branch: ai-doctor-fix-<run_id>
    new_branch = f"ai-doctor-fix-{state['run_id']}"
    create_branch_res = requests.post(
        f"https://api.github.com/repos/{repo}/git/refs",
        headers=headers,
        json={"ref": f"refs/heads/{new_branch}", "sha": base_sha}
    )

    if create_branch_res.status_code not in [201, 422]:
        print(f"Failed to create branch: {create_branch_res.text}")
        state['pr_url'] = "Failed to create PR branch"
        return state

    # 3. Get existing file SHA for test_app.py
    file_info = requests.get(f"https://api.github.com/repos/{repo}/contents/test_app.py?ref={new_branch}", headers=headers).json()
    file_sha = file_info.get('sha', '')

    # 4. Update test_app.py in new branch
    import base64
    content_b64 = base64.b64encode(state['suggested_fix_code'].encode('utf-8')).decode('utf-8')
    
    requests.put(
        f"https://api.github.com/repos/{repo}/contents/test_app.py",
        headers=headers,
        json={
            "message": "fix(ci): auto-resolve test assertion failure via AI Doctor Agent",
            "content": content_b64,
            "sha": file_sha,
            "branch": new_branch
        }
    )

    # 5. Create Pull Request
    pr_body = f"## 🤖 AI DevOps Doctor Automated Fix\n\n### Root Cause Analysis:\n{state['root_cause']}\n\n*This PR was automatically generated by LangGraph Agent.*"
    pr_res = requests.post(
        f"https://api.github.com/repos/{repo}/pulls",
        headers=headers,
        json={
            "title": "🤖 [AI Auto-Fix] Resolve failing pytest suite",
            "head": new_branch,
            "base": "main",
            "body": pr_body
        }
    )

    if pr_res.status_code == 201:
        pr_url = pr_res.json().get('html_url')
        state['pr_url'] = pr_url
        print(f"🎉 PR Successfully Created: {pr_url}")
    else:
        print(f"PR Creation issue: {pr_res.text}")
        state['pr_url'] = "PR creation skipped or failed"

    return state

# LangGraph Build
def build_graph():
    workflow = StateGraph(AgentState)

    workflow.add_node("fetch_logs", fetch_logs_node)
    workflow.add_node("analyze_root_cause", analyze_root_cause_node)
    workflow.add_node("generate_fix", generate_fix_node)
    workflow.add_node("create_pr", create_pr_node)

    workflow.set_entry_point("fetch_logs")
    workflow.add_edge("fetch_logs", "analyze_root_cause")
    workflow.add_edge("analyze_root_cause", "generate_fix")
    workflow.add_edge("generate_fix", "create_pr")
    workflow.add_edge("create_pr", END)

    return workflow.compile()

if __name__ == "__main__":
    initial_state = {
        "repo_name": os.getenv("REPO_NAME", ""),
        "run_id": os.getenv("FAILED_RUN_ID", ""),
        "github_token": os.getenv("GITHUB_TOKEN", ""),
        "parsed_logs": "",
        "root_cause": "",
        "suggested_fix_code": "",
        "pr_url": ""
    }

    app = build_graph()
    app.invoke(initial_state)